# _data/videos.yml
- platform: youtube
  id: wE7I1saBUI0
  title: "Yardie Creek General Use Zone in the Ningaloo Marine Park (State waters)"
- platform: youtube
  id: w_r6nmYzFW8
  title: "Surveying South-west Corner Marine Park’s habitats and fishes"